"""Add region_name col to deployment

Revision ID: 9461be74dd62
Revises: 514c0e87e61f
Create Date: 2024-09-26 16:16:44.486790

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "9461be74dd62"
down_revision = "514c0e87e61f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("deployments", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("provider_type", sa.String(length=128), nullable=True)
        )
        batch_op.add_column(
            sa.Column("region_name", sa.String(length=128), nullable=True)
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("deployments", schema=None) as batch_op:
        batch_op.drop_column("provider_type")
        batch_op.drop_column("region_name")
    # ### end Alembic commands ###
